Repository andela/ah-frontend-dojo, pull requests merged in 2019-05, with the labels that each got.

#1 Chore (React App): Setup an empty react app with airbnb eslinting
  .babelrc
  .eslintrc.json
  .gitignore
  ReadMe.md
  package.json
  src/components/App.js
  src/index.html
  src/index.js
  webpack.config.js
Labels: finished, ready for review

#2 #166280143 Add Pull request template
  .eslintrc.json
  .gitignore
  ReadMe.md
  docs/pull_request_template.md
  package.json
  src/Components/Apps/App.js
  src/index.html
  src/index.js
Labels: ready for merge

#8 #165273518: Setup redux and create appropriate folder structure
  package.json
  src/components/Apps/App.js
  src/index.js
  src/store/actions/types.js
  src/store/rootReducer.js
  src/store/store.js
Labels: finished

#9 #165273519: Setup environment for writing tests
  .eslintrc.json
  .gitignore
  package.json
  src/components/Apps/App.test.js
  src/setupTests.js
Labels: finished

#12 #165273515: Adding hound GitHub integration
  .hound.yml
  .stylelintrc.json
Labels: finished

#10 #65273520: Setting Travis CI
  .DS_Store
  .eslintrc.json
  .travis.yml
  ReadMe.md
Labels: finished

#7 #165273522: Set up Sass processing on the client
  .eslintrc.json
  jest.config.js
  package.json
  src/assets/MainStyle.scss
  src/components/Apps/App.js
  src/components/Apps/App.test.js
  src/components/Apps/__snapshots__/App.test.js.snap
  src/setupTests.js
  webpack.config.js
Labels: finished

#14 165273521: Chore setup router dom
  .eslintrc.json
  .travis.yml
  package.json
  src/components/Apps/App.js
  src/components/Apps/__snapshots__/App.test.js.snap
  src/components/Login/Login.test.js
  src/components/Login/__snapshots__/login.test.js.snap
  src/components/Login/index.js
  src/pages/Error/PageNotFound.test.js
  src/pages/Error/__snapshots__/PageNotFound.test.js.snap
  src/pages/Error/index.js
  src/pages/Landing/Home.test.js
  src/pages/Landing/__snapshots__/home.test.js.snap
  src/pages/Landing/index.js
  src/setupTests.js
  src/store/reducers/authReducer.js
  src/store/rootReducer.js
  src/store/store.js
  webpack.config.js
Labels: finished

#11 #166282663: Deploy the app to heroku
  .babelrc
  ReadMe.md
  package.json
  server.js
  src/index.js
  webpack.config.js
Labels: finished
