Repository andela/ah-frontend-dojo, pull requests merged in 2019-06, with the labels that each got.

#15 166266384: Setup pre-commit and pre-push hooks
  .travis.yml
  commitlint.config.js
  package.json
Labels: finished

#21 #166462564: User should see a landing page
  .DS_Store
  .eslintrc.json
  package.json
  src/assets/images/banner.jpg
  src/assets/images/perfecto-capucine-779224-unsplash.jpg
  src/assets/images/red car.jpg
  src/components/Apps/App.js
  src/components/Apps/__snapshots__/App.test.js.snap
  src/components/ArticlePreview/ArticlePreview.test.js
  src/components/ArticlePreview/index.js
  src/components/Footer/Footer.scss
  src/components/Footer/index.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.test.js
  src/components/NavBar/NavBarStyle.scss
  src/pages/Landing/Home.test.js
  src/pages/Landing/Landing.scss
  src/pages/Landing/Landing.test.js
  src/pages/Landing/__snapshots__/home.test.js.snap
  src/pages/Landing/index.js
  src/store/actions/articleActions.js
  src/store/actions/articleActions.test.js
  src/store/actions/types.js
  src/store/reducers/articles/Articles.test.js
  src/store/reducers/articles/index.js
  src/store/rootReducer.js
  src/utils/index.js
  src/utils/utils.test.js
  webpack.config.js
Labels: finished

#22 #166462564: User should see an improved landing page
  .DS_Store
  .babelrc
  .gitignore
  package.json
  src/assets/MainStyle.scss
  src/assets/images/loader.gif
  src/components/Apps/App.test.js
  src/components/Apps/__snapshots__/App.test.js.snap
  src/components/ArticlePreview/ArticlePreview.scss
  src/components/ArticlePreview/ArticlePreview.test.js
  src/components/ArticlePreview/index.js
  src/components/Footer/Footer.scss
  src/components/Footer/Footer.test.js
  src/components/Footer/index.js
  src/components/Loader/Loader.scss
  src/components/Loader/Loader.test.js
  src/components/Loader/index.js
  src/components/NavBar/NavBar.test.js
  src/components/NavBar/NavBarStyle.scss
  src/components/NavBar/index.js
  src/pages/Landing/ArticleColumn.js
  src/pages/Landing/Landing.scss
  src/pages/Landing/Landing.test.js
  src/pages/Landing/index.js
  src/store/actions/articleActions.test.js
  src/store/actions/articleActions/articleActions.test.js
  src/store/actions/articleActions/index.js
  src/store/actions/articleTypes.js
  src/store/reducers/articles/Articles.test.js
  src/store/reducers/articles/index.js
  src/store/rootReducer.js
  src/utils/index.js
  src/utils/utils.test.js
  webpack.config.js
Labels: finished

#16 165273529: User sign in feature
  package.json
  src/.DS_Store
  src/components/Apps/App.js
  src/components/Login/Login.scss
  src/components/Login/Login.test.js
  src/components/Login/__snapshots__/login.test.js.snap
  src/components/Login/index.js
  src/components/ModalBox/ModalBox.test.js
  src/components/ModalBox/index.js
  src/components/NavBar/NavBar.test.js
  src/components/NavBar/NavBarStyle.scss
  src/components/NavBar/__snapshots__/NavBar.test.js.snap
  src/components/NavBar/index.js
  src/components/SignupForm/SignupForm.test.js
  src/components/SignupForm/__snapshots__/SignupForm.test.js.snap
  src/components/SignupForm/index.js
  src/components/SignupUser/SignupUser.test.js
  src/components/SignupUser/__snapshots__/SignupUser.test.js.snap
  src/components/SignupUser/index.js
  src/constants/staticsMethods.js
  src/index.html
  src/store/actions/__mocks__/index.js
  src/store/actions/index.js
  src/store/actions/loginActions/index.js
  src/store/actions/loginActions/loginActions.test.js
  src/store/actions/loginTypes.js
  src/store/actions/types.js
  src/store/reducers/index.js
  src/store/reducers/loginReducer/index.js
  src/store/reducers/loginReducer/loginReducer.test.js
  src/store/rootReducer.js
  src/utils/index.js
  src/utils/utils.test.js
Labels: finished

#26 #166675204: Refactor user authentication
  package.json
  src/components/Login/Login.scss
  src/components/NavBar/NavBar.test.js
  src/components/NavBar/index.js
  src/store/actions/__mocks__/index.js
  src/store/actions/loginActions/index.js
  src/store/actions/loginActions/loginActions.test.js
  src/store/reducers/loginReducer/index.js
  src/store/reducers/loginReducer/loginReducer.test.js
  src/utils/index.js
  src/utils/utils.test.js
Labels: finished

#24 #165273526: User should be able to reset their password
  package.json
  src/components/Apps/App.js
  src/components/Apps/App.test.js
  src/components/EmailConfirmation/EmailConfirmation.test.js
  src/components/EmailConfirmation/index.js
  src/components/EmailConfirmationForm/EmailConfirmationForm.test.js
  src/components/EmailConfirmationForm/index.js
  src/components/Login/Login.scss
  src/components/Login/__snapshots__/login.test.js.snap
  src/components/Login/index.js
  src/components/NavBar/index.js
  src/constants/constantStrings.js
  src/pages/PasswordReset/PasswordReset.scss
  src/pages/PasswordReset/PasswordReset.test.js
  src/pages/PasswordReset/index.js
  src/store/actions/confirmEmailActions/confirmEmailActions.test.js
  src/store/actions/confirmEmailActions/index.js
  src/store/actions/confirmEmailTypes.js
  src/store/actions/passwordResetTypes.js
  src/store/actions/resetPassword/index.js
  src/store/actions/resetPassword/resetPawwordActions.test.js
  src/store/reducers/confirmEmailReducer/ConfirmEmailReducer.test.js
  src/store/reducers/confirmEmailReducer/index.js
  src/store/reducers/passwordResetReducer/PassowdResetReducer.test.js
  src/store/reducers/passwordResetReducer/index.js
  src/store/rootReducer.js
Labels: finished

#29 #165273526: Password reset enhancement
  src/components/Apps/App.test.js
  src/components/EmailConfirmation/EmailConfirmation.test.js
  src/pages/Landing/index.js
  src/pages/PasswordReset/PasswordReset.test.js
  src/pages/PasswordReset/index.js
  src/store/actions/resetPassword/index.js
  src/store/actions/resetPassword/resetPawwordActions.test.js
Labels: finished

#30 #165273530: social login and register
  .gitignore
  package.json
  server.js
  src/components/Login/__snapshots__/login.test.js.snap
  src/components/Login/index.js
  src/components/NavBar/NavBar.test.js
  src/components/NavBar/index.js
  src/components/Social/Facebook/Facebook.test.js
  src/components/Social/Facebook/FacebookStyle.scss
  src/components/Social/Facebook/__snapshots__/Facebook.test.js.snap
  src/components/Social/Facebook/index.js
  src/components/Social/Google/Google.test.js
  src/components/Social/Google/GoogleStyle.scss
  src/components/Social/Google/__snapshots__/Google.test.js.snap
  src/components/Social/Google/index.js
  src/pages/PasswordReset/PasswordReset.test.js
  src/store/actions/__mocks__/index.js
  src/store/actions/loginActions/index.js
  src/store/actions/socialActions/FacebookActions.js
  src/store/actions/socialActions/FacebookActions.test.js
  src/store/actions/socialActions/GoogleActions.js
  src/store/actions/socialActions/GoogleActions.test.js
  src/store/actions/socialTypes.js
  src/store/actions/types.js
  src/store/reducers/socialReducer/Facebook/facebookReducer.test.js
  src/store/reducers/socialReducer/Facebook/index.js
  src/store/reducers/socialReducer/Google/googleReducer.test.js
  src/store/reducers/socialReducer/Google/index.js
  src/store/rootReducer.js
Labels: ready for review

#37 feat(password reset): user should be able to reset their password
  src/components/ArticlePreview/index.js
  src/components/EmailConfirmationForm/EmailConfirmationForm.test.js
  src/pages/Landing/ArticleColumn.js
  src/pages/Landing/index.js
  src/pages/PasswordReset/PasswordReset.test.js
  src/pages/PasswordReset/index.js
  src/store/actions/confirmEmailActions/confirmEmailActions.test.js
  src/store/actions/resetPassword/resetPasswordActions.test.js
  src/store/reducers/passwordResetReducer/PassowdResetReducer.test.js
Labels: enhancement, ready for review

#19 #165273531: Users should be able to view and edit their profiles
  package.json
  src/assets/MainStyle.scss
  src/components/Apps/App.js
  src/components/NavBar/NavBarStyle.scss
  src/components/NavBar/index.js
  src/components/Profile/Index.js
  src/components/Profile/Profile.scss
  src/components/Profile/Profile.test.js
  src/components/Profile/Setting.scss
  src/components/Profile/Settings.js
  src/components/Profile/Settings.test.js
  src/components/Profile/Sidebar.js
  src/components/Profile/Sidebar.scss
  src/components/Profile/__snapshots__/Profile.test.js.snap
  src/components/Profile/__snapshots__/Settings.test.js.snap
  src/constants/constantStrings.js
  src/firebase/config.js
  src/pages/Profile/Profile.scss
  src/pages/Profile/Profile.test.js
  src/pages/Profile/__snapshots__/Profile.test.js.snap
  src/pages/Profile/index.js
  src/routers/PrivateRoute.js
  src/routers/PrivateRoute.test.js
  src/routers/__snapshots__/PrivateRoute.test.js.snap
  src/store/actions/__mocks__/profile.js
  src/store/actions/profileActions/index.js
  src/store/actions/profileActions/profileActions.test.js
  src/store/actions/types.js
  src/store/reducers/profileReducer/index.js
  src/store/reducers/profileReducer/profileReducer.test.js
  src/store/rootReducer.js
  src/utils/mainAxios.js
  webpack.config.js
Labels: ready for merge

#39 #165273547: Feature list bookmarks
  src/.DS_Store
  src/assets/MainStyle.scss
  src/assets/images/icons8-bookmark-50.png
  src/assets/images/icons8-bookmark-filled-50.png
  src/components/Apps/App.js
  src/components/Apps/App.test.js
  src/components/Profile/Articles.js
  src/components/Profile/Articles.scss
  src/components/Profile/Bookmarks.js
  src/components/Profile/Bookmarks.scss
  src/components/Profile/Index.js
  src/components/Profile/Profile.test.js
  src/components/Profile/__snapshots__/Profile.test.js.snap
  src/pages/PasswordReset/PasswordReset.test.js
  src/store/actions/bookmarkActions/bookmarkActions.test.js
  src/store/actions/bookmarkActions/index.js
  src/store/actions/bookmarkTypes.js
  src/store/reducers/bookmarkReducer/bookmarkReducer.test.js
  src/store/reducers/bookmarkReducer/index.js
  src/store/rootReducer.js
  src/utils/index.js
  webpack.config.js
Labels: finished

#42 feat(error page): add the error page
  src/pages/Error/ErrorPageStyle.scss
  src/pages/Error/__snapshots__/PageNotFound.test.js.snap
  src/pages/Error/index.js
Labels: finished, ready for review
